### ISSUE TITLE
Next button automaticly press when user entered website.

### ISSUE THREAD

**Issue by siravijbb** [wonderfulsoftware/webring#200]
Note:Some case from mobile phone and pc
How to reproduce:
1.Click webring logo alt
2.webring showed and next button some how unexpectedly press after user enter page and preview didn't show same page as user enter from.

**Comment by dtinth** [comment]
This is expected krub — the "ring" button will take user to the next site.

Hope this answers your question krub!

**Comment by siravijbb** [comment]
ok krub, I thought it’s was bug krub!
