### ISSUE TITLE
อยากให้มี Link กลับมาที่ GitHub นี้ครับ

### ISSUE THREAD

**Issue by jittagornp** [wonderfulsoftware/webring#22]
อยากให้ https://webring.wonderful.software/ มี Link กลับมาที่ GitHub นี้   
เพื่อที่เวลาคนที่สนใจเข้าไปที่ Webring แล้วอยากเพิ่ม Website ตัวเองเข้าไป จะได้มาที่ GitHub นี้ถูก

**Comment by dtinth** [comment]
ตอนนี้ในเว็บมีลิงค์ "อ่านเพิ่มเติม" อยู่แล้วครับ แต่เดี๋ยวเย็นๆ มาเพิ่มอีกลิงค์สำหรับ “ร่วมวง” โดยเฉพาะดีกว่า ขอบคุณสำหรับข้อเสนอแนะครับบ

**Comment by jittagornp** [comment]
ขอบคุณครับ พอดีตอนแรกผมมองไม่เห็นคำว่า "[อ่านเพิ่มเติม]" เพราะสีมันกลืนกับ ข้อความ 
(เพราะไม่ได้อ่านทุกตัวอักษร แค่มองผ่าน ๆ)

ชอบคำว่า “ร่วมวง” ครับ

**Comment by dtinth** [comment]
![image](https://user-images.githubusercontent.com/193136/104911117-effd2300-59bc-11eb-933c-f2a34d3e0b66.png)

ใส่ลิงค์ใน Footer แล้วครับ~

**Comment by jittagornp** [comment]
ขอบคุณครับ เห็น Link ขึ้นแล้วครับ
