### ISSUE TITLE
Screenshot cannot render emoji

### ISSUE THREAD

**Issue by dtinth** [wonderfulsoftware/webring#46]
Relevant code is in `automation/site-fetcher`

https://github.com/wonderfulsoftware/webring-site-screenshots/blob/main/heyfirst.co_375w%402x.png

**Comment by heyfirst** [comment]
I guess many people face this problem. Let's see more information in this link. https://github.com/puppeteer/puppeteer/issues/4086

**Comment by dtinth** [comment]
Thanks @aofdev for fixing this in #54!

**Comment by heyfirst** [comment]
Awesome P'Aoffffffffffffffffffffffff @aofdev
