### ISSUE TITLE
Feature request : Check for latest update for each site

### ISSUE THREAD

**Issue by narze** [wonderfulsoftware/webring#53]
Since we have almost half a hundred sites on the ring right now (and I've checked all of them out)
It should be useful if there is some way to know that the site is recently updated.

How can this be done : 
- RSS feed (but required action from each websites, not feasible)
- Check their git (Some aren't using git, not feasible)
- Scrape the page, and diff the image or text (I think this is the most possible way)

**Comment by dtinth** [comment]
@narze I plan to support both 1 and 3 but haven't decided whether to do it in this project or as a separate site. In either case the webring will link to these views.

For no.1 the data file can be used to build an RSS aggregator.

For no.3 right now you have this: https://github.com/wonderfulsoftware/webring-site-screenshots/commits/main so it should be possible to plug directly with GitHub API

**Comment by dtinth** [comment]
@narze This is now being worked on in #82. I decided to use RSS feed. Turns out almost half of the websites in the webring already has a working RSS feed!
