### ISSUE TITLE
Fix failling Cypress end-to-end tests

### ISSUE THREAD

**Issue by dtinth** [wonderfulsoftware/webring#73]
## Background

Currently our E2E test is failing.

Check out Cypress dashboard here:
https://dashboard.cypress.io/projects/77zijk/runs/36/test-results/b340ebf6-f409-492d-86d6-847659c02473

![image](https://user-images.githubusercontent.com/193136/139486483-13bd8261-8e24-43fc-94d4-4dd12ea59004.png)

## Task

- Please fix the failed end-to-end tests.
- Your PR should change a test file that is failing and correct it.
- Please include a screenshot of a Cypress run to verify that the test is fixed.

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

**Comment by ironbyte** [comment]
Hi, I would love to tackle this issue. Please assign it to me thanks

**Comment by dtinth** [comment]
@ironbyte Yours now, thanks for participating! 🙏
